module.exports.LogLevels = {
    FATAL: 'FATAL',
    CRITICAL: 'CRITK',
    ERROR: 'ERROR',
    WARNING: 'WARNG',
    INFO: 'INFO ',
    STINK: 'STINK',
    NOTE: 'NOTE ',
    DEBUG: 'DEBUG',
    SPAM: 'SPAM ',
    FLOOR: 'FLOOR',
    PHASE: 'PHASE',
    OK: 'OK   ',
    KO: 'KO   ',
};